development:
  adapter: async

test:
  adapter: test

production:
  adapter: async

production1:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: remo_sound_production
